[
   {
      "author_association" : "CONTRIBUTOR",
      "body" : "If possible, would be good to add a text explaining why the stop/start calls are fixing the issue.\r\nGuessing that has to do with nodes sync.",
      "created_at" : "2022-08-26T19:23:37Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/pull/25915#issuecomment-1228837580",
      "id" : 1228837580,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/25915",
      "node_id" : "IC_kwDOABII585JPpLM",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1228837580/reactions"
      },
      "updated_at" : "2022-08-26T19:23:37Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1228837580",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/5377650?v=4",
         "events_url" : "https://api.github.com/users/furszy/events{/privacy}",
         "followers_url" : "https://api.github.com/users/furszy/followers",
         "following_url" : "https://api.github.com/users/furszy/following{/other_user}",
         "gists_url" : "https://api.github.com/users/furszy/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/furszy",
         "id" : 5377650,
         "login" : "furszy",
         "node_id" : "MDQ6VXNlcjUzNzc2NTA=",
         "organizations_url" : "https://api.github.com/users/furszy/orgs",
         "received_events_url" : "https://api.github.com/users/furszy/received_events",
         "repos_url" : "https://api.github.com/users/furszy/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/furszy/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/furszy/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/furszy"
      }
   },
   {
      "author_association" : "MEMBER",
      "body" : "> If possible, would be good to add a text explaining why the stop/start calls are fixing the issue. Guessing that has to do with nodes sync.\r\n\r\nThe restart (or stop/start) is part of the original test to empty the mempool. The test can be reworked to just use `generateblock(tx_orig)` instead of the restart, but that can be done in a follow-up. I'll keep the changes here to only fixing the intermittent issue.\r\n\r\nI've pushed an alternative fix that simply removes the redundant (and failing) check.",
      "created_at" : "2022-08-27T10:48:12Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/pull/25915#issuecomment-1229169691",
      "id" : 1229169691,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/25915",
      "node_id" : "IC_kwDOABII585JQ6Qb",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1229169691/reactions"
      },
      "updated_at" : "2022-08-27T10:48:12Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1229169691",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/6399679?v=4",
         "events_url" : "https://api.github.com/users/MarcoFalke/events{/privacy}",
         "followers_url" : "https://api.github.com/users/MarcoFalke/followers",
         "following_url" : "https://api.github.com/users/MarcoFalke/following{/other_user}",
         "gists_url" : "https://api.github.com/users/MarcoFalke/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/MarcoFalke",
         "id" : 6399679,
         "login" : "MarcoFalke",
         "node_id" : "MDQ6VXNlcjYzOTk2Nzk=",
         "organizations_url" : "https://api.github.com/users/MarcoFalke/orgs",
         "received_events_url" : "https://api.github.com/users/MarcoFalke/received_events",
         "repos_url" : "https://api.github.com/users/MarcoFalke/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/MarcoFalke/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/MarcoFalke/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/MarcoFalke"
      }
   },
   {
      "author_association" : "CONTRIBUTOR",
      "body" : "Hmm, under the hood, nodes are syncing data and the tx ends up in the mempool when we are expecting to not have it there (thus why removing the `sync_fun=self.no_op` makes it fail all the time, you force nodes to sync-up).\r\n\r\nProbably, the simplest path to fix the unexpected sync should be something like:\r\n```diff\r\ndiff --git a/test/functional/wallet_balance.py b/test/functional/wallet_balance.py\r\n--- a/test/functional/wallet_balance.py\t(revision a7c7f6d354304521d3a2de04eb57fc74be52b68a)\r\n+++ b/test/functional/wallet_balance.py\t(date 1661606543724)\r\n@@ -262,6 +262,7 @@\r\n         assert_equal(self.nodes[0].getbalance(minconf=0), total_amount)\r\n \r\n         self.log.info('Put txs back into mempool of node 1 (not node 0)')\r\n+        self.disconnect_nodes(0, 1)\r\n         self.nodes[0].invalidateblock(block_reorg)\r\n         self.nodes[1].invalidateblock(block_reorg)\r\n         assert_equal(self.nodes[0].getbalance(minconf=0), 0)  # wallet txs not in the mempool are untrusted\r\n```\r\n\r\n(nodes are, few lines below, re-connected anyway)\r\n\r\nnote: with this change, cannot remove the `sync_fun=self.no_op` from the `generatetoaddress` call as any sync attempt between nodes will fail (they are not longer connected).",
      "created_at" : "2022-08-27T13:34:33Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/pull/25915#issuecomment-1229193770",
      "id" : 1229193770,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/25915",
      "node_id" : "IC_kwDOABII585JRAIq",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1229193770/reactions"
      },
      "updated_at" : "2022-08-27T14:00:49Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1229193770",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/5377650?v=4",
         "events_url" : "https://api.github.com/users/furszy/events{/privacy}",
         "followers_url" : "https://api.github.com/users/furszy/followers",
         "following_url" : "https://api.github.com/users/furszy/following{/other_user}",
         "gists_url" : "https://api.github.com/users/furszy/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/furszy",
         "id" : 5377650,
         "login" : "furszy",
         "node_id" : "MDQ6VXNlcjUzNzc2NTA=",
         "organizations_url" : "https://api.github.com/users/furszy/orgs",
         "received_events_url" : "https://api.github.com/users/furszy/received_events",
         "repos_url" : "https://api.github.com/users/furszy/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/furszy/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/furszy/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/furszy"
      }
   },
   {
      "author_association" : "MEMBER",
      "body" : "> Probably, the simplest path to fix the unexpected sync should be something like:\r\n\r\nYes, that should also work. Though, the second balance check is redundant and not needed, so I think removing it is better than accommodating it.",
      "created_at" : "2022-08-27T15:27:57Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/pull/25915#issuecomment-1229213236",
      "id" : 1229213236,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/25915",
      "node_id" : "IC_kwDOABII585JRE40",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1229213236/reactions"
      },
      "updated_at" : "2022-08-27T15:27:57Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1229213236",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/6399679?v=4",
         "events_url" : "https://api.github.com/users/MarcoFalke/events{/privacy}",
         "followers_url" : "https://api.github.com/users/MarcoFalke/followers",
         "following_url" : "https://api.github.com/users/MarcoFalke/following{/other_user}",
         "gists_url" : "https://api.github.com/users/MarcoFalke/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/MarcoFalke",
         "id" : 6399679,
         "login" : "MarcoFalke",
         "node_id" : "MDQ6VXNlcjYzOTk2Nzk=",
         "organizations_url" : "https://api.github.com/users/MarcoFalke/orgs",
         "received_events_url" : "https://api.github.com/users/MarcoFalke/received_events",
         "repos_url" : "https://api.github.com/users/MarcoFalke/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/MarcoFalke/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/MarcoFalke/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/MarcoFalke"
      }
   },
   {
      "author_association" : "CONTRIBUTOR",
      "body" : "> > Probably, the simplest path to fix the unexpected sync should be something like:\r\n> \r\n> Yes, that should also work. Though, the second balance check is redundant and not needed, so I think removing it is better than accommodating it.\r\n\r\nYeah but with the removal, we are still doubtful over the intermittency cause.\r\n\r\nUp until now, what we know is that the intermittency is related to node1 syncing the mempool with node0. Which means that after generating the block, node0 accepts a tx that was previously rejected (due be \"the third descendant of the tx created above\" ).\r\n\r\nNote, I'm not blocking this, can move forward as is. Just saying that would be nice to describe the intermittency cause in-detail. I think that, sooner or later, the issue can pop-up again in another test case.",
      "created_at" : "2022-08-29T21:07:14Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/pull/25915#issuecomment-1230861889",
      "id" : 1230861889,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/25915",
      "node_id" : "IC_kwDOABII585JXXZB",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1230861889/reactions"
      },
      "updated_at" : "2022-08-29T23:56:34Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1230861889",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/5377650?v=4",
         "events_url" : "https://api.github.com/users/furszy/events{/privacy}",
         "followers_url" : "https://api.github.com/users/furszy/followers",
         "following_url" : "https://api.github.com/users/furszy/following{/other_user}",
         "gists_url" : "https://api.github.com/users/furszy/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/furszy",
         "id" : 5377650,
         "login" : "furszy",
         "node_id" : "MDQ6VXNlcjUzNzc2NTA=",
         "organizations_url" : "https://api.github.com/users/furszy/orgs",
         "received_events_url" : "https://api.github.com/users/furszy/received_events",
         "repos_url" : "https://api.github.com/users/furszy/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/furszy/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/furszy/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/furszy"
      }
   },
   {
      "author_association" : "MEMBER",
      "body" : "ACK fae5bd920007c33de0b794bf2b2d698bfccc12ee",
      "created_at" : "2022-08-31T15:19:40Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/pull/25915#issuecomment-1233079248",
      "id" : 1233079248,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/25915",
      "node_id" : "IC_kwDOABII585Jf0vQ",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1233079248/reactions"
      },
      "updated_at" : "2022-08-31T15:19:40Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1233079248",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/3782274?v=4",
         "events_url" : "https://api.github.com/users/achow101/events{/privacy}",
         "followers_url" : "https://api.github.com/users/achow101/followers",
         "following_url" : "https://api.github.com/users/achow101/following{/other_user}",
         "gists_url" : "https://api.github.com/users/achow101/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/achow101",
         "id" : 3782274,
         "login" : "achow101",
         "node_id" : "MDQ6VXNlcjM3ODIyNzQ=",
         "organizations_url" : "https://api.github.com/users/achow101/orgs",
         "received_events_url" : "https://api.github.com/users/achow101/received_events",
         "repos_url" : "https://api.github.com/users/achow101/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/achow101/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/achow101/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/achow101"
      }
   },
   {
      "author_association" : "MEMBER",
      "body" : "> > > Probably, the simplest path to fix the unexpected sync should be something like:\r\n> > \r\n> > \r\n> > Yes, that should also work. Though, the second balance check is redundant and not needed, so I think removing it is better than accommodating it.\r\n> \r\n> Yeah but with the removal, we are still doubtful over the intermittency cause.\r\n> \r\n> Up until now, what we know is that the intermittency is related to node1 syncing the mempool with node0. Which means that after generating the block, node0 accepts a tx that was previously rejected (due be \"the third descendant of the tx created above\" ).\r\n> \r\n> Note, I'm not blocking this, can move forward as is. Just saying that would be nice to describe the intermittency cause in-detail. I think that, sooner or later, the issue can pop-up again in another test case.\r\n\r\nTo describe the steps as I understand them:\r\n\r\n* `invalidateblock` usually puts the txs in the block back into the mempool, however for node 0 it does not because it has a strict descendant limit of 3.\r\n* After `generatetoaddress` the tx will be put into the mempool again. The reason the test passed most of the time is by pure chance, because apparently the `getbalance` call was faster than tx-trickle.\r\n\r\nThe fix in this pull removes the `getbalance`, because:\r\n\r\n* It is wrong (only passed most of the time by pure chance)\r\n* It is redundant",
      "created_at" : "2022-09-01T08:34:59Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/pull/25915#issuecomment-1233939845",
      "id" : 1233939845,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/25915",
      "node_id" : "IC_kwDOABII585JjG2F",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1233939845/reactions"
      },
      "updated_at" : "2022-09-01T08:34:59Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1233939845",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/6399679?v=4",
         "events_url" : "https://api.github.com/users/MarcoFalke/events{/privacy}",
         "followers_url" : "https://api.github.com/users/MarcoFalke/followers",
         "following_url" : "https://api.github.com/users/MarcoFalke/following{/other_user}",
         "gists_url" : "https://api.github.com/users/MarcoFalke/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/MarcoFalke",
         "id" : 6399679,
         "login" : "MarcoFalke",
         "node_id" : "MDQ6VXNlcjYzOTk2Nzk=",
         "organizations_url" : "https://api.github.com/users/MarcoFalke/orgs",
         "received_events_url" : "https://api.github.com/users/MarcoFalke/received_events",
         "repos_url" : "https://api.github.com/users/MarcoFalke/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/MarcoFalke/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/MarcoFalke/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/MarcoFalke"
      }
   },
   {
      "author_association" : "CONTRIBUTOR",
      "body" : "> To describe the steps as I understand them:\r\n>\r\n> invalidateblock usually puts the txs in the block back into the mempool, however for node 0 it does not because it has a strict descendant limit of 3.\r\nAfter generatetoaddress the tx will be put into the mempool again. The reason the test passed most of the time is by pure chance, because apparently the getbalance call was faster than tx-trickle.\r\nThe fix in this pull removes the getbalance, because:\r\n>\r\n> It is wrong (only passed most of the time by pure chance)\r\n> It is redundant\r\n\r\nOk thanks Marko, now it make sense. I was missing the strict descendant limit.\r\nThen this started happening more often now due #25865 that whitelisted peers by default. All good.",
      "created_at" : "2022-09-01T20:57:13Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/pull/25915#issuecomment-1234773283",
      "id" : 1234773283,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/25915",
      "node_id" : "IC_kwDOABII585JmSUj",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1234773283/reactions"
      },
      "updated_at" : "2022-09-01T20:57:13Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1234773283",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/5377650?v=4",
         "events_url" : "https://api.github.com/users/furszy/events{/privacy}",
         "followers_url" : "https://api.github.com/users/furszy/followers",
         "following_url" : "https://api.github.com/users/furszy/following{/other_user}",
         "gists_url" : "https://api.github.com/users/furszy/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/furszy",
         "id" : 5377650,
         "login" : "furszy",
         "node_id" : "MDQ6VXNlcjUzNzc2NTA=",
         "organizations_url" : "https://api.github.com/users/furszy/orgs",
         "received_events_url" : "https://api.github.com/users/furszy/received_events",
         "repos_url" : "https://api.github.com/users/furszy/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/furszy/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/furszy/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/furszy"
      }
   }
]
