[
   {
      "author_association" : "CONTRIBUTOR",
      "body" : "Ah. This makes sense!\nFixes #8045 not #8051.\nI could not reproduce #8045 but looks good.\n\nutACK 53bcca971b807b25f219f0aeea25071e38ccea7d\n",
      "created_at" : "2016-05-13T17:18:29Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/pull/8052#issuecomment-219105087",
      "id" : 219105087,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/8052",
      "node_id" : "MDEyOklzc3VlQ29tbWVudDIxOTEwNTA4Nw==",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/219105087/reactions"
      },
      "updated_at" : "2016-05-13T17:18:29Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/219105087",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/178464?v=4",
         "events_url" : "https://api.github.com/users/jonasschnelli/events{/privacy}",
         "followers_url" : "https://api.github.com/users/jonasschnelli/followers",
         "following_url" : "https://api.github.com/users/jonasschnelli/following{/other_user}",
         "gists_url" : "https://api.github.com/users/jonasschnelli/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/jonasschnelli",
         "id" : 178464,
         "login" : "jonasschnelli",
         "node_id" : "MDQ6VXNlcjE3ODQ2NA==",
         "organizations_url" : "https://api.github.com/users/jonasschnelli/orgs",
         "received_events_url" : "https://api.github.com/users/jonasschnelli/received_events",
         "repos_url" : "https://api.github.com/users/jonasschnelli/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/jonasschnelli/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/jonasschnelli/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/jonasschnelli"
      }
   },
   {
      "author_association" : "MEMBER",
      "body" : "This does not fix #8045 for me.\n",
      "created_at" : "2016-05-13T19:11:33Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/pull/8052#issuecomment-219134037",
      "id" : 219134037,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/8052",
      "node_id" : "MDEyOklzc3VlQ29tbWVudDIxOTEzNDAzNw==",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/219134037/reactions"
      },
      "updated_at" : "2016-05-13T19:11:33Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/219134037",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/548488?v=4",
         "events_url" : "https://api.github.com/users/sipa/events{/privacy}",
         "followers_url" : "https://api.github.com/users/sipa/followers",
         "following_url" : "https://api.github.com/users/sipa/following{/other_user}",
         "gists_url" : "https://api.github.com/users/sipa/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/sipa",
         "id" : 548488,
         "login" : "sipa",
         "node_id" : "MDQ6VXNlcjU0ODQ4OA==",
         "organizations_url" : "https://api.github.com/users/sipa/orgs",
         "received_events_url" : "https://api.github.com/users/sipa/received_events",
         "repos_url" : "https://api.github.com/users/sipa/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/sipa/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/sipa/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/sipa"
      }
   },
   {
      "author_association" : "CONTRIBUTOR",
      "body" : "Hm. I can't reliably reproduce the test failure; I got it to happen once by looping `walletbackup.py` until it failed, but the problem's too intermittent here for me to test a solution effectively.\n\nIn the error case, packet capture showed:\nt+0s: `importwallet` request to server\nt+30.5s: FIN+ACK from client\nt+38.5s: reply from server, followed by FIN+ACK from server\n\nSo it looks like it involves a 30 second timeout somewhere on the client end, but since `53bcca9` didn't fix it apparently the problem timeout's value is not originating with `HTTP_TIMEOUT`...\n\n[[I should probably modify this to extend the timeout only for the test case in question, but let's figure out why it isn't working first]]\n",
      "created_at" : "2016-05-13T19:41:55Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/pull/8052#issuecomment-219140717",
      "id" : 219140717,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/8052",
      "node_id" : "MDEyOklzc3VlQ29tbWVudDIxOTE0MDcxNw==",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/219140717/reactions"
      },
      "updated_at" : "2016-05-13T19:48:22Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/219140717",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/1047859?v=4",
         "events_url" : "https://api.github.com/users/kazcw/events{/privacy}",
         "followers_url" : "https://api.github.com/users/kazcw/followers",
         "following_url" : "https://api.github.com/users/kazcw/following{/other_user}",
         "gists_url" : "https://api.github.com/users/kazcw/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/kazcw",
         "id" : 1047859,
         "login" : "kazcw",
         "node_id" : "MDQ6VXNlcjEwNDc4NTk=",
         "organizations_url" : "https://api.github.com/users/kazcw/orgs",
         "received_events_url" : "https://api.github.com/users/kazcw/received_events",
         "repos_url" : "https://api.github.com/users/kazcw/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/kazcw/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/kazcw/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/kazcw"
      }
   },
   {
      "author_association" : "MEMBER",
      "body" : "I tried with HTTP_TIMEOUT=600, and walletbackup.py still fails reliably. #8051 fixes it.\n",
      "created_at" : "2016-05-13T19:54:18Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/pull/8052#issuecomment-219143416",
      "id" : 219143416,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/8052",
      "node_id" : "MDEyOklzc3VlQ29tbWVudDIxOTE0MzQxNg==",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/219143416/reactions"
      },
      "updated_at" : "2016-05-13T19:54:18Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/219143416",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/548488?v=4",
         "events_url" : "https://api.github.com/users/sipa/events{/privacy}",
         "followers_url" : "https://api.github.com/users/sipa/followers",
         "following_url" : "https://api.github.com/users/sipa/following{/other_user}",
         "gists_url" : "https://api.github.com/users/sipa/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/sipa",
         "id" : 548488,
         "login" : "sipa",
         "node_id" : "MDQ6VXNlcjU0ODQ4OA==",
         "organizations_url" : "https://api.github.com/users/sipa/orgs",
         "received_events_url" : "https://api.github.com/users/sipa/received_events",
         "repos_url" : "https://api.github.com/users/sipa/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/sipa/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/sipa/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/sipa"
      }
   },
   {
      "author_association" : "MEMBER",
      "body" : "Hmm, I think this might be related: https://github.com/bitcoin/bitcoin/pull/6695\n\n@sipa Does it fix it for you if you start bitcoind with a bigger `-rpcservertimeout`?\n",
      "created_at" : "2016-05-13T19:57:31Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/pull/8052#issuecomment-219144149",
      "id" : 219144149,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/8052",
      "node_id" : "MDEyOklzc3VlQ29tbWVudDIxOTE0NDE0OQ==",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/219144149/reactions"
      },
      "updated_at" : "2016-05-13T19:57:31Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/219144149",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/7463573?v=4",
         "events_url" : "https://api.github.com/users/sdaftuar/events{/privacy}",
         "followers_url" : "https://api.github.com/users/sdaftuar/followers",
         "following_url" : "https://api.github.com/users/sdaftuar/following{/other_user}",
         "gists_url" : "https://api.github.com/users/sdaftuar/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/sdaftuar",
         "id" : 7463573,
         "login" : "sdaftuar",
         "node_id" : "MDQ6VXNlcjc0NjM1NzM=",
         "organizations_url" : "https://api.github.com/users/sdaftuar/orgs",
         "received_events_url" : "https://api.github.com/users/sdaftuar/received_events",
         "repos_url" : "https://api.github.com/users/sdaftuar/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/sdaftuar/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/sdaftuar/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/sdaftuar"
      }
   },
   {
      "author_association" : "CONTRIBUTOR",
      "body" : "Oh, the bug in #8051 occurs during send. This fixes a bug in receiving...\n",
      "created_at" : "2016-05-13T20:03:23Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/pull/8052#issuecomment-219145456",
      "id" : 219145456,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/8052",
      "node_id" : "MDEyOklzc3VlQ29tbWVudDIxOTE0NTQ1Ng==",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/219145456/reactions"
      },
      "updated_at" : "2016-05-13T20:06:49Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/219145456",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/1047859?v=4",
         "events_url" : "https://api.github.com/users/kazcw/events{/privacy}",
         "followers_url" : "https://api.github.com/users/kazcw/followers",
         "following_url" : "https://api.github.com/users/kazcw/following{/other_user}",
         "gists_url" : "https://api.github.com/users/kazcw/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/kazcw",
         "id" : 1047859,
         "login" : "kazcw",
         "node_id" : "MDQ6VXNlcjEwNDc4NTk=",
         "organizations_url" : "https://api.github.com/users/kazcw/orgs",
         "received_events_url" : "https://api.github.com/users/kazcw/received_events",
         "repos_url" : "https://api.github.com/users/kazcw/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/kazcw/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/kazcw/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/kazcw"
      }
   },
   {
      "author_association" : "MEMBER",
      "body" : "@sdaftuar That works!\n",
      "created_at" : "2016-05-13T21:36:58Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/pull/8052#issuecomment-219165455",
      "id" : 219165455,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/8052",
      "node_id" : "MDEyOklzc3VlQ29tbWVudDIxOTE2NTQ1NQ==",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/219165455/reactions"
      },
      "updated_at" : "2016-05-13T21:36:58Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/219165455",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/548488?v=4",
         "events_url" : "https://api.github.com/users/sipa/events{/privacy}",
         "followers_url" : "https://api.github.com/users/sipa/followers",
         "following_url" : "https://api.github.com/users/sipa/following{/other_user}",
         "gists_url" : "https://api.github.com/users/sipa/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/sipa",
         "id" : 548488,
         "login" : "sipa",
         "node_id" : "MDQ6VXNlcjU0ODQ4OA==",
         "organizations_url" : "https://api.github.com/users/sipa/orgs",
         "received_events_url" : "https://api.github.com/users/sipa/received_events",
         "repos_url" : "https://api.github.com/users/sipa/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/sipa/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/sipa/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/sipa"
      }
   },
   {
      "author_association" : "MEMBER",
      "body" : "I tried with HTTP_TIMEOUT=1, and walletbackup.py still works fine.\n",
      "created_at" : "2016-05-15T06:31:42Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/pull/8052#issuecomment-219269140",
      "id" : 219269140,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/8052",
      "node_id" : "MDEyOklzc3VlQ29tbWVudDIxOTI2OTE0MA==",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/219269140/reactions"
      },
      "updated_at" : "2016-05-15T06:31:42Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/219269140",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/6399679?v=4",
         "events_url" : "https://api.github.com/users/MarcoFalke/events{/privacy}",
         "followers_url" : "https://api.github.com/users/MarcoFalke/followers",
         "following_url" : "https://api.github.com/users/MarcoFalke/following{/other_user}",
         "gists_url" : "https://api.github.com/users/MarcoFalke/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/MarcoFalke",
         "id" : 6399679,
         "login" : "MarcoFalke",
         "node_id" : "MDQ6VXNlcjYzOTk2Nzk=",
         "organizations_url" : "https://api.github.com/users/MarcoFalke/orgs",
         "received_events_url" : "https://api.github.com/users/MarcoFalke/received_events",
         "repos_url" : "https://api.github.com/users/MarcoFalke/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/MarcoFalke/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/MarcoFalke/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/MarcoFalke"
      }
   },
   {
      "author_association" : "CONTRIBUTOR",
      "body" : "This is the error (after `INFO: Restoring using dumped wallet`):\n\n```\nUnexpected exception caught during testing: timeout('timed out',)\n  File \"/bitcoin/qa/rpc-tests/test_framework/test_framework.py\", line 138, in main\n    self.run_test()\n  File \"./walletbackup.py\", line 188, in run_test\n    self.nodes[0].importwallet(tmpdir + \"/node0/wallet.dump\")\n  File \"/bitcoin/qa/rpc-tests/test_framework/coverage.py\", line 49, in __call__\n    return_val = self.auth_service_proxy_instance.__call__(*args, **kwargs)\n  File \"/bitcoin/qa/rpc-tests/test_framework/authproxy.py\", line 137, in __call__\n    response = self._request('POST', self.__url.path, postdata)\n  File \"/bitcoin/qa/rpc-tests/test_framework/authproxy.py\", line 119, in _request\n    return self._get_response()\n  File \"/bitcoin/qa/rpc-tests/test_framework/authproxy.py\", line 152, in _get_response\n    http_response = self.__conn.getresponse()\n  File \"/usr/lib64/python3.4/http/client.py\", line 1171, in getresponse\n    response.begin()\n  File \"/usr/lib64/python3.4/http/client.py\", line 351, in begin\n    version, status, reason = self._read_status()\n  File \"/usr/lib64/python3.4/http/client.py\", line 313, in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n  File \"/usr/lib64/python3.4/socket.py\", line 374, in readinto\n    return self._sock.recv_into(b)\nStopping nodes\nWARN: Unable to stop node: CannotSendRequest('Request-sent',)\n```\n\nIt doesn't happen often when my machine is otherwise idle; I looped the test for several hours (originally trying to reproduce the other bug) and got two failures. With the machine under heavy load it happens consistently (all failures look just like the above backtrace).\n\nWhen I set `HTTP_TIMEOUT=1` it fails in an earlier `recv_into` (in various rpc calls).\n",
      "created_at" : "2016-05-15T15:17:26Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/pull/8052#issuecomment-219291658",
      "id" : 219291658,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/8052",
      "node_id" : "MDEyOklzc3VlQ29tbWVudDIxOTI5MTY1OA==",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/219291658/reactions"
      },
      "updated_at" : "2016-05-15T15:17:26Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/219291658",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/1047859?v=4",
         "events_url" : "https://api.github.com/users/kazcw/events{/privacy}",
         "followers_url" : "https://api.github.com/users/kazcw/followers",
         "following_url" : "https://api.github.com/users/kazcw/following{/other_user}",
         "gists_url" : "https://api.github.com/users/kazcw/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/kazcw",
         "id" : 1047859,
         "login" : "kazcw",
         "node_id" : "MDQ6VXNlcjEwNDc4NTk=",
         "organizations_url" : "https://api.github.com/users/kazcw/orgs",
         "received_events_url" : "https://api.github.com/users/kazcw/received_events",
         "repos_url" : "https://api.github.com/users/kazcw/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/kazcw/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/kazcw/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/kazcw"
      }
   },
   {
      "author_association" : "MEMBER",
      "body" : "As this doesn't fix the issue, we should probably close it?\n\nIf we need this I'd prefer to not change the default value in `authproxy.py` but supply a different timeout where the object is created instead.\n",
      "created_at" : "2016-05-31T13:49:26Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/pull/8052#issuecomment-222693840",
      "id" : 222693840,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/8052",
      "node_id" : "MDEyOklzc3VlQ29tbWVudDIyMjY5Mzg0MA==",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/222693840/reactions"
      },
      "updated_at" : "2016-05-31T13:50:18Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/222693840",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/126646?v=4",
         "events_url" : "https://api.github.com/users/laanwj/events{/privacy}",
         "followers_url" : "https://api.github.com/users/laanwj/followers",
         "following_url" : "https://api.github.com/users/laanwj/following{/other_user}",
         "gists_url" : "https://api.github.com/users/laanwj/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/laanwj",
         "id" : 126646,
         "login" : "laanwj",
         "node_id" : "MDQ6VXNlcjEyNjY0Ng==",
         "organizations_url" : "https://api.github.com/users/laanwj/orgs",
         "received_events_url" : "https://api.github.com/users/laanwj/received_events",
         "repos_url" : "https://api.github.com/users/laanwj/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/laanwj/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/laanwj/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/laanwj"
      }
   },
   {
      "author_association" : "CONTRIBUTOR",
      "body" : "Yeah, this is too intermittent to worry about; it only came up because I was grinding the test to look for that other bug.\n",
      "created_at" : "2016-06-01T17:40:49Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/pull/8052#issuecomment-223069297",
      "id" : 223069297,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/8052",
      "node_id" : "MDEyOklzc3VlQ29tbWVudDIyMzA2OTI5Nw==",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/223069297/reactions"
      },
      "updated_at" : "2016-06-01T17:40:49Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/223069297",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/1047859?v=4",
         "events_url" : "https://api.github.com/users/kazcw/events{/privacy}",
         "followers_url" : "https://api.github.com/users/kazcw/followers",
         "following_url" : "https://api.github.com/users/kazcw/following{/other_user}",
         "gists_url" : "https://api.github.com/users/kazcw/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/kazcw",
         "id" : 1047859,
         "login" : "kazcw",
         "node_id" : "MDQ6VXNlcjEwNDc4NTk=",
         "organizations_url" : "https://api.github.com/users/kazcw/orgs",
         "received_events_url" : "https://api.github.com/users/kazcw/received_events",
         "repos_url" : "https://api.github.com/users/kazcw/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/kazcw/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/kazcw/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/kazcw"
      }
   }
]
