[
   {
      "author_association" : "MEMBER",
      "body" : "Could you also add the line where the assertion failed (from the python\ntraceback, which should be in the stderr)\n\nOn Fri, Jul 29, 2016 at 10:23 AM, Wladimir J. van der Laan <\nnotifications@github.com> wrote:\n\n> I had this problem once while I was running the walletbackup.py test on\n> 0.13:\n> \n> walletbackup.py:\n> Initializing test directory /tmp/testo3khmc00/37\n> INFO: Generating initial blockchain\n> Assertion failed: 76.69962300 != 50\n> Stopping nodes\n> Not cleaning up dir /tmp/testo3khmc00/37\n> Failed\n> \n> I'm unfortunately unable to reproduce it again, looks like a race\n> condition.\n> \n> â\n> You are receiving this because you are subscribed to this thread.\n> Reply to this email directly, view it on GitHub\n> https://github.com/bitcoin/bitcoin/issues/8425, or mute the thread\n> https://github.com/notifications/unsubscribe-auth/AGGmv60NSH-svLHtS9wi2s23c_U3ZQlBks5qabiRgaJpZM4JX-fm\n> .\n",
      "created_at" : "2016-07-29T08:51:56Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/8425#issuecomment-236128606",
      "id" : 236128606,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/8425",
      "node_id" : "MDEyOklzc3VlQ29tbWVudDIzNjEyODYwNg==",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/236128606/reactions"
      },
      "updated_at" : "2016-07-29T08:51:56Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/236128606",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/6399679?v=4",
         "events_url" : "https://api.github.com/users/MarcoFalke/events{/privacy}",
         "followers_url" : "https://api.github.com/users/MarcoFalke/followers",
         "following_url" : "https://api.github.com/users/MarcoFalke/following{/other_user}",
         "gists_url" : "https://api.github.com/users/MarcoFalke/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/MarcoFalke",
         "id" : 6399679,
         "login" : "MarcoFalke",
         "node_id" : "MDQ6VXNlcjYzOTk2Nzk=",
         "organizations_url" : "https://api.github.com/users/MarcoFalke/orgs",
         "received_events_url" : "https://api.github.com/users/MarcoFalke/received_events",
         "repos_url" : "https://api.github.com/users/MarcoFalke/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/MarcoFalke/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/MarcoFalke/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/MarcoFalke"
      }
   },
   {
      "author_association" : "MEMBER",
      "body" : "@MarcoFalke done\n",
      "created_at" : "2016-07-29T08:57:13Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/8425#issuecomment-236129647",
      "id" : 236129647,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/8425",
      "node_id" : "MDEyOklzc3VlQ29tbWVudDIzNjEyOTY0Nw==",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/236129647/reactions"
      },
      "updated_at" : "2016-07-29T08:57:13Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/236129647",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/126646?v=4",
         "events_url" : "https://api.github.com/users/laanwj/events{/privacy}",
         "followers_url" : "https://api.github.com/users/laanwj/followers",
         "following_url" : "https://api.github.com/users/laanwj/following{/other_user}",
         "gists_url" : "https://api.github.com/users/laanwj/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/laanwj",
         "id" : 126646,
         "login" : "laanwj",
         "node_id" : "MDQ6VXNlcjEyNjY0Ng==",
         "organizations_url" : "https://api.github.com/users/laanwj/orgs",
         "received_events_url" : "https://api.github.com/users/laanwj/received_events",
         "repos_url" : "https://api.github.com/users/laanwj/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/laanwj/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/laanwj/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/laanwj"
      }
   },
   {
      "author_association" : "MEMBER",
      "body" : "I've also seen walletbackup.py fail, but it's a different error.\n\n```\n...Traceback (most recent call last):\n  File \"qa/pull-tester/rpc-tests.py\", line 342, in <module>\n    runtests()\n  File \"qa/pull-tester/rpc-tests.py\", line 211, in runtests\n    (name, stdout, stderr, passed, duration) = job_queue.get_next()\n  File \"qa/pull-tester/rpc-tests.py\", line 266, in get_next\n    (stdout, stderr) = proc.communicate(timeout=3)\n  File \"/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py\", line 1072, in communicate\n    stdout, stderr = self._communicate(input, endtime, timeout)\n  File \"/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py\", line 1716, in _communicate\n    self._check_timeout(endtime, orig_timeout)\n  File \"/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py\", line 1098, in _check_timeout\n    raise TimeoutExpired(self.args, orig_timeout)\nsubprocess.TimeoutExpired: Command '['/Users/xxx/github/bitcoin/qa/rpc-tests/walletbackup.py', '--srcdir=/Users/xxx/github/bitcoin/src', '--portseed=39']' timed out after 3 seconds\n```\n\n```\nTraceback (most recent call last):\n  File \"qa/pull-tester/rpc-tests.py\", line 342, in <module>\n    runtests()\n  File \"qa/pull-tester/rpc-tests.py\", line 211, in runtests\n    (name, stdout, stderr, passed, duration) = job_queue.get_next()\n  File \"qa/pull-tester/rpc-tests.py\", line 266, in get_next\n    (stdout, stderr) = proc.communicate(timeout=3)\n  File \"/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py\", line 1072, in communicate\n    stdout, stderr = self._communicate(input, endtime, timeout)\n  File \"/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py\", line 1716, in _communicate\n    self._check_timeout(endtime, orig_timeout)\n  File \"/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py\", line 1098, in _check_timeout\n    raise TimeoutExpired(self.args, orig_timeout)\nsubprocess.TimeoutExpired: Command '['/Users/xxx/github/bitcoin/qa/rpc-tests/wallet-dump.py', '--srcdir=/Users/xxx/github/bitcoin/src', '--portseed=35']' timed out after 3 seconds\n```\n",
      "created_at" : "2016-08-01T02:09:29Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/8425#issuecomment-236474246",
      "id" : 236474246,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/8425",
      "node_id" : "MDEyOklzc3VlQ29tbWVudDIzNjQ3NDI0Ng==",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/236474246/reactions"
      },
      "updated_at" : "2016-08-01T02:09:29Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/236474246",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/863730?v=4",
         "events_url" : "https://api.github.com/users/fanquake/events{/privacy}",
         "followers_url" : "https://api.github.com/users/fanquake/followers",
         "following_url" : "https://api.github.com/users/fanquake/following{/other_user}",
         "gists_url" : "https://api.github.com/users/fanquake/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/fanquake",
         "id" : 863730,
         "login" : "fanquake",
         "node_id" : "MDQ6VXNlcjg2MzczMA==",
         "organizations_url" : "https://api.github.com/users/fanquake/orgs",
         "received_events_url" : "https://api.github.com/users/fanquake/received_events",
         "repos_url" : "https://api.github.com/users/fanquake/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/fanquake/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/fanquake/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/fanquake"
      }
   },
   {
      "author_association" : "MEMBER",
      "body" : "```\nwalletbackup.py:\nInitializing test directory /var/folders/rb/jqqd25w926s5429rf58_zsv00000gn/T/test34w8is11/39\nUnexpected exception caught during testing: Exception('bitcoind exited with status -6 during initialization',)\nStopping nodes\n\nstderr:\n Error: Unable to start HTTP server. See debug log for details.\nAssertion failed: (nThreadsServicingQueue == 0), function ~CScheduler, file scheduler.cpp, line 19.\nError: Unable to start HTTP server. See debug log for details.\n  File \"/Users/xxx/Github/bitcoin/qa/rpc-tests/test_framework/test_framework.py\", line 146, in main\n    self.setup_network()\n  File \"/Users/xxx/github/bitcoin/qa/rpc-tests/walletbackup.py\", line 53, in setup_network\n    self.nodes = start_nodes(self.num_nodes, self.options.tmpdir, extra_args)\n  File \"/Users/xxx/Github/bitcoin/qa/rpc-tests/test_framework/util.py\", line 340, in start_nodes\n    rpcs.append(start_node(i, dirname, extra_args[i], rpchost, binary=binary[i]))\n  File \"/Users/xxx/Github/bitcoin/qa/rpc-tests/test_framework/util.py\", line 321, in start_node\n    wait_for_bitcoind_start(bitcoind_processes[i], url, i)\n  File \"/Users/xxx/Github/bitcoin/qa/rpc-tests/test_framework/util.py\", line 191, in wait_for_bitcoind_start\n    raise Exception('bitcoind exited with status %i during initialization' % process.returncode)\nTraceback (most recent call last):\n  File \"/Users/xxx/github/bitcoin/qa/rpc-tests/walletbackup.py\", line 201, in <module>\n    WalletBackupTest().main()\n  File \"/Users/xxx/Github/bitcoin/qa/rpc-tests/test_framework/test_framework.py\", line 169, in main\n    stop_nodes(self.nodes)\n  File \"/Users/xxx/Github/bitcoin/qa/rpc-tests/test_framework/util.py\", line 358, in stop_nodes\n    for node in nodes:\nTypeError: 'NoneType' object is not iterable\n\nPass: False, Duration: 11 s\n```\n",
      "created_at" : "2016-08-01T02:14:24Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/8425#issuecomment-236474724",
      "id" : 236474724,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/8425",
      "node_id" : "MDEyOklzc3VlQ29tbWVudDIzNjQ3NDcyNA==",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/236474724/reactions"
      },
      "updated_at" : "2016-08-01T02:15:31Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/236474724",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/863730?v=4",
         "events_url" : "https://api.github.com/users/fanquake/events{/privacy}",
         "followers_url" : "https://api.github.com/users/fanquake/followers",
         "following_url" : "https://api.github.com/users/fanquake/following{/other_user}",
         "gists_url" : "https://api.github.com/users/fanquake/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/fanquake",
         "id" : 863730,
         "login" : "fanquake",
         "node_id" : "MDQ6VXNlcjg2MzczMA==",
         "organizations_url" : "https://api.github.com/users/fanquake/orgs",
         "received_events_url" : "https://api.github.com/users/fanquake/received_events",
         "repos_url" : "https://api.github.com/users/fanquake/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/fanquake/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/fanquake/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/fanquake"
      }
   },
   {
      "author_association" : "CONTRIBUTOR",
      "body" : "I'm seeing this pretty frequently, seems to be part of why https://github.com/bitcoin/bitcoin/pull/8464 is failing.\n",
      "created_at" : "2016-08-07T18:16:09Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/8425#issuecomment-238098597",
      "id" : 238098597,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/8425",
      "node_id" : "MDEyOklzc3VlQ29tbWVudDIzODA5ODU5Nw==",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/238098597/reactions"
      },
      "updated_at" : "2016-08-07T18:16:09Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/238098597",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/886523?v=4",
         "events_url" : "https://api.github.com/users/JeremyRubin/events{/privacy}",
         "followers_url" : "https://api.github.com/users/JeremyRubin/followers",
         "following_url" : "https://api.github.com/users/JeremyRubin/following{/other_user}",
         "gists_url" : "https://api.github.com/users/JeremyRubin/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/JeremyRubin",
         "id" : 886523,
         "login" : "JeremyRubin",
         "node_id" : "MDQ6VXNlcjg4NjUyMw==",
         "organizations_url" : "https://api.github.com/users/JeremyRubin/orgs",
         "received_events_url" : "https://api.github.com/users/JeremyRubin/received_events",
         "repos_url" : "https://api.github.com/users/JeremyRubin/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/JeremyRubin/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/JeremyRubin/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/JeremyRubin"
      }
   },
   {
      "author_association" : "CONTRIBUTOR",
      "body" : "I think you're right it is a race condition. To test the hypothesis, we can try running with a lot of workers, which should hopefully increase the probability of failure.\n\nRunning `./rpc_tests.py -parallel=40` on master gives me:\n\n```\nTEST                           | PASSED | DURATION\n\np2p-fullblocktest.py           | True   | 174 s\nwalletbackup.py                | False  | 9 s\nbip68-112-113-p2p.py           | True   | 34 s\nwallet.py                      | False  | 1 s\nwallet-hd.py                   | False  | 33 s\nwallet-dump.py                 | True   | 7 s\nlisttransactions.py            | True   | 38 s\nreceivedby.py                  | True   | 18 s\nmempool_resurrect_test.py      | True   | 1 s\ntxn_doublespend.py --mineblock | True   | 4 s\ntxn_clone.py                   | True   | 3 s\ngetchaintips.py                | True   | 10 s\nrawtransactions.py             | False  | 15 s\nrest.py                        | False  | 62 s\nmempool_spendcoinbase.py       | True   | 1 s\nmempool_reorg.py               | True   | 6 s\nmempool_limit.py               | False  | 4 s\nhttpbasics.py                  | True   | 1 s\nmulti_rpc.py                   | True   | 3 s\nzapwallettxes.py               | False  | 13 s\nproxy_test.py                  | True   | 2 s\nmerkle_blocks.py               | False  | 5 s\nfundrawtransaction.py          | False  | 23 s\nsignrawtransactions.py         | True   | 2 s\nnodehandling.py                | True   | 14 s\nreindex.py                     | True   | 12 s\ndecodescript.py                | True   | 0 s\nblockchain.py                  | False  | 1 s\ndisablewallet.py               | True   | 3 s\nsendheaders.py                 | True   | 29 s\nkeypool.py                     | True   | 5 s\nprioritise_transaction.py      | False  | 4 s\ninvalidblockrequest.py         | True   | 5 s\ninvalidtxrequest.py            | True   | 4 s\nabandonconflict.py             | False  | 14 s\np2p-versionbits-warning.py     | False  | 7 s\np2p-segwit.py                  | False  | 10 s\nsegwit.py                      | False  | 4 s\nimportprunedfunds.py           | False  | 3 s\nsignmessages.py                | True   | 2 s\np2p-compactblocks.py           | False  | 13 s\nzmq_test.py                    | False  | 0 s\n\nALL                            | False  | 599 s (accumulated)\n```\n\nEach one of these failures logs an `Error: Unable to start HTTP server. See debug log for details.`.\n\nThis supports the hypothesis that it's a race condition.\n\nWhen I ran with `-parallel=1` on my branch, I still observed a (`Error: Unable to start HTTP server. See debug log for details.`) on rawtransaction (see https://github.com/bitcoin/bitcoin/pull/8464).\nSo this means that it's likely not a race condition in the main test code (which should run in serial as per @MarcoFalke's suggestion), but perhaps in some cleanup code which locks the bitcoind starting.\n\nHope that helps track this down, still not sure exactly where it is.\n",
      "created_at" : "2016-08-08T02:17:33Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/8425#issuecomment-238127542",
      "id" : 238127542,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/8425",
      "node_id" : "MDEyOklzc3VlQ29tbWVudDIzODEyNzU0Mg==",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/238127542/reactions"
      },
      "updated_at" : "2016-08-08T02:17:33Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/238127542",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/886523?v=4",
         "events_url" : "https://api.github.com/users/JeremyRubin/events{/privacy}",
         "followers_url" : "https://api.github.com/users/JeremyRubin/followers",
         "following_url" : "https://api.github.com/users/JeremyRubin/following{/other_user}",
         "gists_url" : "https://api.github.com/users/JeremyRubin/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/JeremyRubin",
         "id" : 886523,
         "login" : "JeremyRubin",
         "node_id" : "MDQ6VXNlcjg4NjUyMw==",
         "organizations_url" : "https://api.github.com/users/JeremyRubin/orgs",
         "received_events_url" : "https://api.github.com/users/JeremyRubin/received_events",
         "repos_url" : "https://api.github.com/users/JeremyRubin/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/JeremyRubin/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/JeremyRubin/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/JeremyRubin"
      }
   },
   {
      "author_association" : "MEMBER",
      "body" : "Interesting, I was hoping the walletbackup fail has been fixed by  #8139 (related discussion in #8052)\n\n> ./rpc_tests.py -parallel=40\n\nRunning all tests in parallel may cause failures due to OOM or out of space (depending how your temp directory is set up).\n",
      "created_at" : "2016-08-08T07:16:13Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/8425#issuecomment-238158852",
      "id" : 238158852,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/8425",
      "node_id" : "MDEyOklzc3VlQ29tbWVudDIzODE1ODg1Mg==",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/238158852/reactions"
      },
      "updated_at" : "2016-08-08T07:16:13Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/238158852",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/6399679?v=4",
         "events_url" : "https://api.github.com/users/MarcoFalke/events{/privacy}",
         "followers_url" : "https://api.github.com/users/MarcoFalke/followers",
         "following_url" : "https://api.github.com/users/MarcoFalke/following{/other_user}",
         "gists_url" : "https://api.github.com/users/MarcoFalke/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/MarcoFalke",
         "id" : 6399679,
         "login" : "MarcoFalke",
         "node_id" : "MDQ6VXNlcjYzOTk2Nzk=",
         "organizations_url" : "https://api.github.com/users/MarcoFalke/orgs",
         "received_events_url" : "https://api.github.com/users/MarcoFalke/received_events",
         "repos_url" : "https://api.github.com/users/MarcoFalke/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/MarcoFalke/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/MarcoFalke/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/MarcoFalke"
      }
   },
   {
      "author_association" : "CONTRIBUTOR",
      "body" : "Hm it's possible my failures were related to not properly clearing bitcoind pids... I'll check.\n",
      "created_at" : "2016-08-08T18:45:42Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/8425#issuecomment-238336926",
      "id" : 238336926,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/8425",
      "node_id" : "MDEyOklzc3VlQ29tbWVudDIzODMzNjkyNg==",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/238336926/reactions"
      },
      "updated_at" : "2016-08-08T18:45:42Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/238336926",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/886523?v=4",
         "events_url" : "https://api.github.com/users/JeremyRubin/events{/privacy}",
         "followers_url" : "https://api.github.com/users/JeremyRubin/followers",
         "following_url" : "https://api.github.com/users/JeremyRubin/following{/other_user}",
         "gists_url" : "https://api.github.com/users/JeremyRubin/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/JeremyRubin",
         "id" : 886523,
         "login" : "JeremyRubin",
         "node_id" : "MDQ6VXNlcjg4NjUyMw==",
         "organizations_url" : "https://api.github.com/users/JeremyRubin/orgs",
         "received_events_url" : "https://api.github.com/users/JeremyRubin/received_events",
         "repos_url" : "https://api.github.com/users/JeremyRubin/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/JeremyRubin/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/JeremyRubin/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/JeremyRubin"
      }
   },
   {
      "author_association" : "MEMBER",
      "body" : "This just failed on travis due to insufficient funds:\n\n```\n   File \"/home/travis/build/bitcoin/bitcoin/qa/rpc-tests/test_framework/test_framework.py\", line 148, in main\n    self.run_test()\n  File \"/home/travis/build/bitcoin/bitcoin/build/../qa/rpc-tests/walletbackup.py\", line 122, in run_test\n    self.do_one_round()\n  File \"/home/travis/build/bitcoin/bitcoin/build/../qa/rpc-tests/walletbackup.py\", line 74, in do_one_round\n    self.one_send(1, a2)\n  File \"/home/travis/build/bitcoin/bitcoin/build/../qa/rpc-tests/walletbackup.py\", line 64, in one_send\n    self.nodes[from_node].sendtoaddress(to_address, amount)\n  File \"/home/travis/build/bitcoin/bitcoin/qa/rpc-tests/test_framework/coverage.py\", line 49, in __call__\n    return_val = self.auth_service_proxy_instance.__call__(*args, **kwargs)\n  File \"/home/travis/build/bitcoin/bitcoin/qa/rpc-tests/test_framework/authproxy.py\", line 146, in __call__\n    raise JSONRPCException(response['error'])\n```\n",
      "created_at" : "2016-08-15T19:31:30Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/8425#issuecomment-239903864",
      "id" : 239903864,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/8425",
      "node_id" : "MDEyOklzc3VlQ29tbWVudDIzOTkwMzg2NA==",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/239903864/reactions"
      },
      "updated_at" : "2016-08-15T19:31:30Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/239903864",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/6399679?v=4",
         "events_url" : "https://api.github.com/users/MarcoFalke/events{/privacy}",
         "followers_url" : "https://api.github.com/users/MarcoFalke/followers",
         "following_url" : "https://api.github.com/users/MarcoFalke/following{/other_user}",
         "gists_url" : "https://api.github.com/users/MarcoFalke/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/MarcoFalke",
         "id" : 6399679,
         "login" : "MarcoFalke",
         "node_id" : "MDQ6VXNlcjYzOTk2Nzk=",
         "organizations_url" : "https://api.github.com/users/MarcoFalke/orgs",
         "received_events_url" : "https://api.github.com/users/MarcoFalke/received_events",
         "repos_url" : "https://api.github.com/users/MarcoFalke/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/MarcoFalke/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/MarcoFalke/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/MarcoFalke"
      }
   }
]
