{
   "active_lock_reason" : null,
   "assignee" : null,
   "assignees" : [],
   "author_association" : "MEMBER",
   "body" : "Noticed on NetBSD, but the same issue could happen on any other system. The issue is outputting the `Reducing -maxconnections` warning during startup:\r\n\r\nhttps://github.com/bitcoin/bitcoin/blob/2f37b221d183dfc8136fa71730acb8f218ad0dcb/src/init.cpp#L893-L898\r\n\r\nWhich causes the tests to abort, due to unexpected output:\r\n```bash\r\npython3.9 test/functional/test_runner.py --jobs=3           \r\nTemporary test directory at /tmp/test_runner_â¿_ð_20220104_002803\r\nRunning Unit Tests for Test Framework Modules\r\n..........\r\n----------------------------------------------------------------------\r\nRan 10 tests in 1.310s\r\n\r\nOK\r\nTraceback (most recent call last):\r\n  File \"/home/ec2-user/bitcoin/test/functional/create_cache.py\", line 27, in <module>\r\n    CreateCache().main()\r\n  File \"/home/ec2-user/bitcoin/test/functional/test_framework/test_framework.py\", line 155, in main\r\n    exit_code = self.shutdown()\r\n  File \"/home/ec2-user/bitcoin/test/functional/test_framework/test_framework.py\", line 304, in shutdown\r\n    self.stop_nodes()\r\n  File \"/home/ec2-user/bitcoin/test/functional/test_framework/test_framework.py\", line 555, in stop_nodes\r\n    node.stop_node(wait=wait, wait_until_stopped=False)\r\n  File \"/home/ec2-user/bitcoin/test/functional/test_framework/test_node.py\", line 336, in stop_node\r\n    self.stop(wait=wait)\r\n  File \"/home/ec2-user/bitcoin/test/functional/test_framework/coverage.py\", line 49, in __call__\r\n    return_val = self.auth_service_proxy_instance.__call__(*args, **kwargs)\r\n  File \"/home/ec2-user/bitcoin/test/functional/test_framework/authproxy.py\", line 142, in __call__\r\n    response, status = self._request('POST', self.__url.path, postdata.encode('utf-8'))\r\n  File \"/home/ec2-user/bitcoin/test/functional/test_framework/authproxy.py\", line 107, in _request\r\n    self.__conn.request(method, path, postdata, headers)\r\n  File \"/usr/pkg/lib/python3.9/http/client.py\", line 1279, in request\r\n    self._send_request(method, url, body, headers, encode_chunked)\r\n  File \"/usr/pkg/lib/python3.9/http/client.py\", line 1325, in _send_request\r\n    self.endheaders(body, encode_chunked=encode_chunked)\r\n  File \"/usr/pkg/lib/python3.9/http/client.py\", line 1274, in endheaders\r\n    self._send_output(message_body, encode_chunked=encode_chunked)\r\n  File \"/usr/pkg/lib/python3.9/http/client.py\", line 1034, in _send_output\r\n    self.send(msg)\r\n  File \"/usr/pkg/lib/python3.9/http/client.py\", line 974, in send\r\n    self.connect()\r\n  File \"/usr/pkg/lib/python3.9/http/client.py\", line 945, in connect\r\n    self.sock = self._create_connection(\r\n  File \"/usr/pkg/lib/python3.9/socket.py\", line 844, in create_connection\r\n    raise err\r\n  File \"/usr/pkg/lib/python3.9/socket.py\", line 832, in create_connection\r\n    sock.connect(sa)\r\nConnectionRefusedError: [Errno 61] Connection refused\r\n2022-01-04T00:28:04.864000Z TestFramework (INFO): Initializing test directory /tmp/test_runner_â¿_ð_20220104_002803/cache\r\n2022-01-04T00:28:05.605000Z TestFramework (ERROR): Assertion failed\r\nTraceback (most recent call last):\r\n  File \"/home/ec2-user/bitcoin/test/functional/test_framework/test_framework.py\", line 131, in main\r\n    self.setup()\r\n  File \"/home/ec2-user/bitcoin/test/functional/test_framework/test_framework.py\", line 287, in setup\r\n    self.setup_chain()\r\n  File \"/home/ec2-user/bitcoin/test/functional/test_framework/test_framework.py\", line 378, in setup_chain\r\n    self._initialize_chain()\r\n  File \"/home/ec2-user/bitcoin/test/functional/test_framework/test_framework.py\", line 792, in _initialize_chain\r\n    self.stop_nodes()\r\n  File \"/home/ec2-user/bitcoin/test/functional/test_framework/test_framework.py\", line 555, in stop_nodes\r\n    node.stop_node(wait=wait, wait_until_stopped=False)\r\n  File \"/home/ec2-user/bitcoin/test/functional/test_framework/test_node.py\", line 350, in stop_node\r\n    raise AssertionError(\"Unexpected stderr {} != {}\".format(stderr, expected_stderr))\r\nAssertionError: Unexpected stderr Warning: Reducing -maxconnections from 125 to 96, because of system limitations. != \r\n2022-01-04T00:28:05.663000Z TestFramework (INFO): Stopping nodes\r\n[node 0] Cleaning up leftover process\r\n```",
   "closed_at" : null,
   "closed_by" : null,
   "comments" : 0,
   "comments_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/23968/comments",
   "created_at" : "2022-01-04T06:23:39Z",
   "events_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/23968/events",
   "html_url" : "https://github.com/bitcoin/bitcoin/issues/23968",
   "id" : 1093048890,
   "labels" : [
      {
         "color" : "d4c5f9",
         "default" : false,
         "description" : null,
         "id" : 62963516,
         "name" : "Tests",
         "node_id" : "MDU6TGFiZWw2Mjk2MzUxNg==",
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/labels/Tests"
      }
   ],
   "labels_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/23968/labels{/name}",
   "locked" : false,
   "milestone" : null,
   "node_id" : "I_kwDOABII585BJpo6",
   "number" : 23968,
   "performed_via_github_app" : null,
   "reactions" : {
      "+1" : 0,
      "-1" : 0,
      "confused" : 0,
      "eyes" : 0,
      "heart" : 0,
      "hooray" : 0,
      "laugh" : 0,
      "rocket" : 0,
      "total_count" : 0,
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/23968/reactions"
   },
   "repository_url" : "https://api.github.com/repos/bitcoin/bitcoin",
   "state" : "open",
   "timeline_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/23968/timeline",
   "title" : "test: functional tests fail to start if -maxconnections is reduced",
   "updated_at" : "2022-01-04T06:23:39Z",
   "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/23968",
   "user" : {
      "avatar_url" : "https://avatars.githubusercontent.com/u/863730?v=4",
      "events_url" : "https://api.github.com/users/fanquake/events{/privacy}",
      "followers_url" : "https://api.github.com/users/fanquake/followers",
      "following_url" : "https://api.github.com/users/fanquake/following{/other_user}",
      "gists_url" : "https://api.github.com/users/fanquake/gists{/gist_id}",
      "gravatar_id" : "",
      "html_url" : "https://github.com/fanquake",
      "id" : 863730,
      "login" : "fanquake",
      "node_id" : "MDQ6VXNlcjg2MzczMA==",
      "organizations_url" : "https://api.github.com/users/fanquake/orgs",
      "received_events_url" : "https://api.github.com/users/fanquake/received_events",
      "repos_url" : "https://api.github.com/users/fanquake/repos",
      "site_admin" : false,
      "starred_url" : "https://api.github.com/users/fanquake/starred{/owner}{/repo}",
      "subscriptions_url" : "https://api.github.com/users/fanquake/subscriptions",
      "type" : "User",
      "url" : "https://api.github.com/users/fanquake"
   }
}
