[
   {
      "author_association" : "CONTRIBUTOR",
      "body" : "There are is already a check to avoid connecting to an already connected address. See:\r\n\r\nhttps://github.com/bitcoin/bitcoin/issues/22559#issuecomment-903851322 and\r\nhttps://bitcoin.stackexchange.com/a/116097/129003\r\n\r\nWhat you are observing is probably due to the race in that check described above. For the second screenshot I guess what happened is that while you initiated the manual connection, after the connection attempt started, but before it completed an automatic outbound was initiated to the same address and later that address connected to us for the inbound :disappointed:. This is not I2P specific, but more likely to be seen with I2P because establishing a connection takes longer.\r\n\r\nWhat I think can be improved:\r\n\r\n* After accepting an incoming connection, drop it if we already have a connection to the same address (ignore the port).\r\n* Fix the race by maintaining a list of \"attempting to connect to\" addresses and do not initiate more connections to them.\r\n* Or maybe, periodically, e.g. every 5 minutes, check for duplicates in `CConnman::m_nodes` and drop the redundant ones, maybe ignoring the port.",
      "created_at" : "2022-11-23T13:43:05Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/26537#issuecomment-1325086601",
      "id" : 1325086601,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/26537",
      "node_id" : "IC_kwDOABII585O-zeJ",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1325086601/reactions"
      },
      "updated_at" : "2022-11-23T13:43:05Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1325086601",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/266751?v=4",
         "events_url" : "https://api.github.com/users/vasild/events{/privacy}",
         "followers_url" : "https://api.github.com/users/vasild/followers",
         "following_url" : "https://api.github.com/users/vasild/following{/other_user}",
         "gists_url" : "https://api.github.com/users/vasild/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/vasild",
         "id" : 266751,
         "login" : "vasild",
         "node_id" : "MDQ6VXNlcjI2Njc1MQ==",
         "organizations_url" : "https://api.github.com/users/vasild/orgs",
         "received_events_url" : "https://api.github.com/users/vasild/received_events",
         "repos_url" : "https://api.github.com/users/vasild/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/vasild/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/vasild/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/vasild"
      }
   },
   {
      "author_association" : "CONTRIBUTOR",
      "body" : "Preventing incoming connections from an address we already have a connection to could block legit cases where multiple distinct nodes run behind a common address. At first I thought that this is ok, since the disconnected node will find another random peer to connect to. But then, having multiple connections with the same address, even if it is the same node, is a minor issue too. Maybe not worth the effort to change that. Or do only for I2P.",
      "created_at" : "2022-11-24T10:09:00Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/26537#issuecomment-1326229242",
      "id" : 1326229242,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/26537",
      "node_id" : "IC_kwDOABII585PDKb6",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1326229242/reactions"
      },
      "updated_at" : "2022-11-24T10:09:00Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1326229242",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/266751?v=4",
         "events_url" : "https://api.github.com/users/vasild/events{/privacy}",
         "followers_url" : "https://api.github.com/users/vasild/followers",
         "following_url" : "https://api.github.com/users/vasild/following{/other_user}",
         "gists_url" : "https://api.github.com/users/vasild/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/vasild",
         "id" : 266751,
         "login" : "vasild",
         "node_id" : "MDQ6VXNlcjI2Njc1MQ==",
         "organizations_url" : "https://api.github.com/users/vasild/orgs",
         "received_events_url" : "https://api.github.com/users/vasild/received_events",
         "repos_url" : "https://api.github.com/users/vasild/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/vasild/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/vasild/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/vasild"
      }
   },
   {
      "author_association" : "CONTRIBUTOR",
      "body" : ">  For the second screenshot I guess what happened is that while you initiated the manual connection, after the connection attempt started, but before it completed an automatic outbound was initiated to the same address and later that address connected to us for the inbound ð\r\n\r\nI will try to reproduce this with `deubg=net` although I agree something similar happened as you described.",
      "created_at" : "2022-11-24T20:21:01Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/26537#issuecomment-1326815282",
      "id" : 1326815282,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/26537",
      "node_id" : "IC_kwDOABII585PFZgy",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1326815282/reactions"
      },
      "updated_at" : "2022-11-24T20:22:00Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1326815282",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/94559964?v=4",
         "events_url" : "https://api.github.com/users/1440000bytes/events{/privacy}",
         "followers_url" : "https://api.github.com/users/1440000bytes/followers",
         "following_url" : "https://api.github.com/users/1440000bytes/following{/other_user}",
         "gists_url" : "https://api.github.com/users/1440000bytes/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/1440000bytes",
         "id" : 94559964,
         "login" : "1440000bytes",
         "node_id" : "U_kgDOBaLe3A",
         "organizations_url" : "https://api.github.com/users/1440000bytes/orgs",
         "received_events_url" : "https://api.github.com/users/1440000bytes/received_events",
         "repos_url" : "https://api.github.com/users/1440000bytes/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/1440000bytes/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/1440000bytes/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/1440000bytes"
      }
   },
   {
      "author_association" : "CONTRIBUTOR",
      "body" : "> Fix the race by maintaining a list of \"attempting to connect to\" addresses and do not initiate more connections to them.\r\n\r\nThis makes sense.",
      "created_at" : "2022-11-24T20:21:51Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/26537#issuecomment-1326815701",
      "id" : 1326815701,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/26537",
      "node_id" : "IC_kwDOABII585PFZnV",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1326815701/reactions"
      },
      "updated_at" : "2022-11-24T20:21:51Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1326815701",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/94559964?v=4",
         "events_url" : "https://api.github.com/users/1440000bytes/events{/privacy}",
         "followers_url" : "https://api.github.com/users/1440000bytes/followers",
         "following_url" : "https://api.github.com/users/1440000bytes/following{/other_user}",
         "gists_url" : "https://api.github.com/users/1440000bytes/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/1440000bytes",
         "id" : 94559964,
         "login" : "1440000bytes",
         "node_id" : "U_kgDOBaLe3A",
         "organizations_url" : "https://api.github.com/users/1440000bytes/orgs",
         "received_events_url" : "https://api.github.com/users/1440000bytes/received_events",
         "repos_url" : "https://api.github.com/users/1440000bytes/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/1440000bytes/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/1440000bytes/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/1440000bytes"
      }
   },
   {
      "author_association" : "CONTRIBUTOR",
      "body" : "> > For the second screenshot I guess what happened is that while you initiated the manual connection, after the connection attempt started, but before it completed an automatic outbound was initiated to the same address and later that address connected to us for the inbound ð\r\n> \r\n> I will try to reproduce this with `deubg=net` although I agree something similar happened as you described.\r\n\r\nIssue is intermittent and I couldn't collect any useful logs. ",
      "created_at" : "2022-11-26T19:49:25Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/26537#issuecomment-1328104066",
      "id" : 1328104066,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/26537",
      "node_id" : "IC_kwDOABII585PKUKC",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1328104066/reactions"
      },
      "updated_at" : "2022-11-26T19:49:25Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1328104066",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/94559964?v=4",
         "events_url" : "https://api.github.com/users/1440000bytes/events{/privacy}",
         "followers_url" : "https://api.github.com/users/1440000bytes/followers",
         "following_url" : "https://api.github.com/users/1440000bytes/following{/other_user}",
         "gists_url" : "https://api.github.com/users/1440000bytes/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/1440000bytes",
         "id" : 94559964,
         "login" : "1440000bytes",
         "node_id" : "U_kgDOBaLe3A",
         "organizations_url" : "https://api.github.com/users/1440000bytes/orgs",
         "received_events_url" : "https://api.github.com/users/1440000bytes/received_events",
         "repos_url" : "https://api.github.com/users/1440000bytes/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/1440000bytes/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/1440000bytes/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/1440000bytes"
      }
   }
]
