{
   "assignee" : null,
   "assignees" : [],
   "author_association" : "NONE",
   "body" : "When using `bitcoin-cli` command `gettxout`, the program does not return an error if the utxo queried doesn't exist.  I initially found this behavior a bit confusing, as in command line contexts a command not returning anything usually means \"it worked\".  Similar calls like `getmempoolentry` will return `Transaction not in mempool` errors, so I expected something like that from `gettxout`.\r\n\r\n**Expected behavior**\r\n\r\n(maybe this is more like \"desired\" behavior)\r\nHow about something like:\r\n```\r\nuser@computer:~$ bitcoin-cli gettxout 0e3e2357e806b6cdb1f70b54c3a3a17b6714ee1f0e68bebb44a74b1efd512098 1\r\nerror code: -5\r\nerror message:\r\nTransaction output not found\r\nuser@computer:~$\r\n```\r\n\r\n**Actual behavior**\r\n```\r\nuser@computer:~$ bitcoin-cli gettxout 0e3e2357e806b6cdb1f70b54c3a3a17b6714ee1f0e68bebb44a74b1efd512098 0\r\n{\r\n  \"bestblock\": \"00000000000000000000b2320e348d60a5eb0532a1fe67bddd197077f7782637\",\r\n  \"confirmations\": 623664,\r\n  \"value\": 50.00000000,\r\n  \"scriptPubKey\": {\r\n    \"asm\": \"0496b538e853519c726a2c91e61ec11600ae1390813a627c66fb8be7947be63c52da7589379515d4e0a604f8141781e62294721166bf621e73a82cbf2342c858ee OP_CHECKSIG\",\r\n    \"hex\": \"410496b538e853519c726a2c91e61ec11600ae1390813a627c66fb8be7947be63c52da7589379515d4e0a604f8141781e62294721166bf621e73a82cbf2342c858eeac\",\r\n    \"type\": \"pubkey\"\r\n  },\r\n  \"coinbase\": true\r\n}\r\nuser@computer:~$ bitcoin-cli gettxout 0e3e2357e806b6cdb1f70b54c3a3a17b6714ee1f0e68bebb44a74b1efd512098 1\r\nuser@computer:~$\r\n```\r\n**To reproduce**\r\n\r\nQuery any non-exsistent utxo with `gettxout`.  Nothing happens, and the program returns with no error.\r\n\r\n**System information**\r\n\r\nUbuntu 18.04.3 LTS, Bitcoin Core 0.19.01\r\n\r\n**Fix?**\r\nIs there a reason why either the RPC call itself or `bitcoin-cli` doesn't return an error in this case?  If so, or if it's complicated to fix, then the lack of an error message isn't not a big deal, and I can close this or leave it around as a \"yeah maybe should fix that someday\".  If it's just an omission however, I'd be happy to open a PR changing it to return some kind of error message.\r\n\r\n",
   "closed_at" : null,
   "closed_by" : null,
   "comments" : 3,
   "comments_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/18476/comments",
   "created_at" : "2020-03-30T22:01:54Z",
   "events_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/18476/events",
   "html_url" : "https://github.com/bitcoin/bitcoin/issues/18476",
   "id" : 590626780,
   "labels" : [
      {
         "color" : "FBBAAB",
         "default" : false,
         "description" : null,
         "id" : 64585,
         "name" : "Bug",
         "node_id" : "MDU6TGFiZWw2NDU4NQ==",
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/labels/Bug"
      }
   ],
   "labels_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/18476/labels{/name}",
   "locked" : false,
   "milestone" : null,
   "node_id" : "MDU6SXNzdWU1OTA2MjY3ODA=",
   "number" : 18476,
   "repository_url" : "https://api.github.com/repos/bitcoin/bitcoin",
   "state" : "open",
   "title" : "bitcoin-cli returns no error on unsuccessful gettxout call",
   "updated_at" : "2020-03-30T22:18:46Z",
   "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/18476",
   "user" : {
      "avatar_url" : "https://avatars3.githubusercontent.com/u/22841402?v=4",
      "events_url" : "https://api.github.com/users/adiabat/events{/privacy}",
      "followers_url" : "https://api.github.com/users/adiabat/followers",
      "following_url" : "https://api.github.com/users/adiabat/following{/other_user}",
      "gists_url" : "https://api.github.com/users/adiabat/gists{/gist_id}",
      "gravatar_id" : "",
      "html_url" : "https://github.com/adiabat",
      "id" : 22841402,
      "login" : "adiabat",
      "node_id" : "MDQ6VXNlcjIyODQxNDAy",
      "organizations_url" : "https://api.github.com/users/adiabat/orgs",
      "received_events_url" : "https://api.github.com/users/adiabat/received_events",
      "repos_url" : "https://api.github.com/users/adiabat/repos",
      "site_admin" : false,
      "starred_url" : "https://api.github.com/users/adiabat/starred{/owner}{/repo}",
      "subscriptions_url" : "https://api.github.com/users/adiabat/subscriptions",
      "type" : "User",
      "url" : "https://api.github.com/users/adiabat"
   }
}
