{
   "assignee" : null,
   "assignees" : [],
   "author_association" : "NONE",
   "body" : "<!-- Describe the issue -->\r\nWhen synching from blocks already available on disk on startup from a old utxo set, bitcoind become unresponsive during the UpdateTip phase:\r\n```\r\n2019-07-07T18:46:49Z UpdateTip: new best=00000000000000000028b702b9da76f700cf3da9682553090f485a7281e57922 height=577001 version=0x20000000 log2_work=90.65784 tx=415579661 date='2019-05-21T00:23:35Z' progress=0.964693 cache=1.5MiB(11777txo)\r\n2019-07-07T18:46:53Z UpdateTip: new best=0000000000000000001113e97e93bd818554382f16d089a81371c6873a0b92b6 height=577003 version=0x20000000 log2_work=90.657883 tx=415584870 date='2019-05-21T00:36:11Z' progress=0.964699 cache=4.2MiB(30674txo)\r\n2019-07-07T18:46:54Z UpdateTip: new best=00000000000000000004cc44be2e12e8a8af7d5a70d35a319c0d95fdce3521e6 height=577004 version=0x20000000 log2_work=90.657904 tx=415586975 date='2019-05-21T00:36:35Z' progress=0.964700 cache=5.3MiB(39842txo)\r\n2019-07-07T18:46:56Z UpdateTip: new best=0000000000000000000a7e3b417edb0f5f01d91bdc36d16a9c374917fc647183 height=577005 version=0x20000000 log2_work=90.657926 tx=415589783 date='2019-05-21T00:51:43Z' progress=0.964707 cache=6.3MiB(47978txo)\r\n2019-07-07T18:46:57Z UpdateTip: new best=00000000000000000012bd7a61b374bf4d58f3e780a309df05bbdca40e45d1a5 height=577006 version=0x20000000 log2_work=90.657947 tx=415592867 date='2019-05-21T01:07:04Z' progress=0.964715 cache=7.8MiB(56907txo)\r\n```\r\n\r\n<!--- What behavior did you expect? -->\r\nI expect either it to work or to get an error like it's the case when trying to run a cli command during the \"Verifying last 6 blocks at level 3\" phase \r\n```\r\nerror code: -28\r\nerror message:\r\n\r\nVerifying blocks...\r\n```\r\n\r\n<!--- What was the actual behavior (provide screenshots if the issue is GUI-related)? -->\r\nInstead, I get the following timeout when trying to run this command: \r\n```\r\nbitcoin-cli.exe getbestblockhash\r\nerror: Could not connect to the server 127.0.0.1:8332 (error code 0 - \"timeout reached\")\r\n\r\nMake sure the bitcoind server is running and that you are connecting to the correct RPC port.\r\n```\r\n\r\n<!--- How reliably can you reproduce the issue, what are the steps to do so? -->\r\nThis append every time I tried to run a command against it, either it be gettxoutsetinfo or invalidateblock\r\nTo reproduce the issue yourself you can <!--- either -->: \r\n- run the following bash script (with a few changes according to your own setup)\r\n âï¸ backup your chainstate/blocks folder before or set DATADIR/DATA_PATH variable to a new location âï¸ \r\nThis script require a bunch of disk space available. \r\nWhat it does is basically download & import a chainstate synched at height = 577000 and around ~8go of blocks up to height 583832\r\n<!--- - or invalidate a good number of blocks yourself (since the bug is during the UpdateTip phase you need to have the time for the cli to timeout), wait for the rewind of the utxo-set to finish, reconsider the block, and then restart the daemon. This should put you in a similar state with a bunch of blocks ready to be loaded from disk. -->\r\n```\r\n#!/bin/bash\r\n\r\nDATADIR_PATH=\"~/.bitcoin/\"\r\nDATADIR=\"\"\r\n# DATADIR=\"-datadir=$DATADIR_PATH\" \r\nBITCOIND_OPTION_NO_NETWORK=\"-maxconnections=0 -par=-7 -rpcthreads=1 -noconnect -listenonion=0 -disablewallet\" \r\n\r\nBITCOIND_OPTIONS=\"$DATADIR\"\r\nBITCOIN_CLI=\"bitcoin-cli\"\r\nBITCOIND=\"bitcoind\"\r\nHASH_INVALIDATE=\"00000000000000000028b702b9da76f700cf3da9682553090f485a7281e57922\"\r\nHASH_SERIALIZED_SERVER=\"7c7acc44bdb316db0a1c26c189a7b5b22be567864cb3e6f72e941fd8892f2f67\"\r\nBLOCK_HEIGHT=\"577000\"\r\nBLOCKS_FILE=\"chain-pruned.tar.gz\"\r\n\r\nwget https://downloads.bitcoinsocialsync.com/utxo-set/utxo-set-$BLOCK_HEIGHT.tar.gz\r\nwget https://downloads.bitcoinsocialsync.com/blockchain/$BLOCKS_FILE\r\n\r\necho \"\"$DATADIR_PATH\"chainstate directory already exist. Deleting...\"\r\nrm -rf \"$DATADIR_PATH\"chainstate\r\necho \"chainstate deleted.\"\r\necho \"\"$DATADIR_PATH\"blocks directory already exist. Deleting...\"\r\nrm -rf \"$DATADIR_PATH\"blocks\r\necho \"blocks deleted.\"\r\n\r\necho \"Extracting utxo-set-$BLOCK_HEIGHT.tar.gz to \"$DATADIR_PATH\"chainstate...\"\r\ntar -zxf utxo-set-$BLOCK_HEIGHT.tar.gz -C \"$DATADIR_PATH\"\r\necho \"Extracting finished.\"\r\necho \"Extracting $BLOCKS_FILE to \"$DATADIR_PATH\"blocks...\"\r\ntar -zxf $BLOCKS_FILE -C \"$DATADIR_PATH\"\r\necho \"Extracting finished.\"\r\n\r\necho \"Launching bitcoind with initial import...\"\r\n$BITCOIND $BITCOIND_OPTIONS $BITCOIND_OPTION_NO_NETWORK &> bitcoind.log &\r\nsleep 6m # wait for startup phase to finish\r\n$BITCOIN_CLI invalidateblock $HASH_INVALIDATE\r\n$BITCOIN_CLI gettxoutsetinfo\r\n```\r\n\r\n<!-- What version of Bitcoin Core are you using, where did you get it (website, self-compiled, etc)? -->\r\nPre-compiled version of Bitcoin Core v0.18.0\r\n\r\n<!-- What type of machine are you observing the error on (OS/CPU and disk type)? -->\r\nbitcoind/cli are installed on the Windows 10 side on a hard drive but all commands are run through WSL, this setup works fine for everything else but that.\r\n\r\n<!-- Any extra information that might be useful in the debugging process. -->\r\n<!--- This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred. -->\r\nhttps://gist.githubusercontent.com/SylTi/7e7801e65f355edba3c460731a740d48/raw/bd81624934c42fb2cc45f0aabca3ca0386a516c7/bitcoind.log if you search for \"invalid block\" you will see some pretty weird stuff. Like the block height going up, then down, then up again.\r\nThis happend when the command I tried to run on the CLI was `invalidateblock 00000000000000000028b702b9da76f700cf3da9682553090f485a7281e57922` but it also timeout so it shouldn't have affected the sync? And if it did work while showing me a timeout, why did the sync restart after the block was invalidated?",
   "closed_at" : "2020-04-26T17:09:45Z",
   "closed_by" : {
      "avatar_url" : "https://avatars0.githubusercontent.com/u/6399679?v=4",
      "events_url" : "https://api.github.com/users/MarcoFalke/events{/privacy}",
      "followers_url" : "https://api.github.com/users/MarcoFalke/followers",
      "following_url" : "https://api.github.com/users/MarcoFalke/following{/other_user}",
      "gists_url" : "https://api.github.com/users/MarcoFalke/gists{/gist_id}",
      "gravatar_id" : "",
      "html_url" : "https://github.com/MarcoFalke",
      "id" : 6399679,
      "login" : "MarcoFalke",
      "node_id" : "MDQ6VXNlcjYzOTk2Nzk=",
      "organizations_url" : "https://api.github.com/users/MarcoFalke/orgs",
      "received_events_url" : "https://api.github.com/users/MarcoFalke/received_events",
      "repos_url" : "https://api.github.com/users/MarcoFalke/repos",
      "site_admin" : false,
      "starred_url" : "https://api.github.com/users/MarcoFalke/starred{/owner}{/repo}",
      "subscriptions_url" : "https://api.github.com/users/MarcoFalke/subscriptions",
      "type" : "User",
      "url" : "https://api.github.com/users/MarcoFalke"
   },
   "comments" : 13,
   "comments_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/16353/comments",
   "created_at" : "2019-07-08T10:36:30Z",
   "events_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/16353/events",
   "html_url" : "https://github.com/bitcoin/bitcoin/issues/16353",
   "id" : 465181912,
   "labels" : [
      {
         "color" : "0052cc",
         "default" : false,
         "description" : null,
         "id" : 98279177,
         "name" : "RPC/REST/ZMQ",
         "node_id" : "MDU6TGFiZWw5ODI3OTE3Nw==",
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/labels/RPC/REST/ZMQ"
      }
   ],
   "labels_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/16353/labels{/name}",
   "locked" : false,
   "milestone" : null,
   "node_id" : "MDU6SXNzdWU0NjUxODE5MTI=",
   "number" : 16353,
   "repository_url" : "https://api.github.com/repos/bitcoin/bitcoin",
   "state" : "closed",
   "title" : "Bitcoind become unresponsive to CLI during UpdateTip phase.",
   "updated_at" : "2020-04-26T17:09:45Z",
   "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/16353",
   "user" : {
      "avatar_url" : "https://avatars0.githubusercontent.com/u/1770876?v=4",
      "events_url" : "https://api.github.com/users/SylTi/events{/privacy}",
      "followers_url" : "https://api.github.com/users/SylTi/followers",
      "following_url" : "https://api.github.com/users/SylTi/following{/other_user}",
      "gists_url" : "https://api.github.com/users/SylTi/gists{/gist_id}",
      "gravatar_id" : "",
      "html_url" : "https://github.com/SylTi",
      "id" : 1770876,
      "login" : "SylTi",
      "node_id" : "MDQ6VXNlcjE3NzA4NzY=",
      "organizations_url" : "https://api.github.com/users/SylTi/orgs",
      "received_events_url" : "https://api.github.com/users/SylTi/received_events",
      "repos_url" : "https://api.github.com/users/SylTi/repos",
      "site_admin" : false,
      "starred_url" : "https://api.github.com/users/SylTi/starred{/owner}{/repo}",
      "subscriptions_url" : "https://api.github.com/users/SylTi/subscriptions",
      "type" : "User",
      "url" : "https://api.github.com/users/SylTi"
   }
}
